// Seed list of known Ohio bands, compiled via research (Bandcamp Daily scene
// reports, label rosters, venue interview blogs, Wikipedia cross-references,
// and user-supplied research). This is the candidate pool for matching -
// restricting candidates to this list is what enforces "actually in Ohio"
// now that Spotify has no location data and AI search was too costly.

module.exports = [
  '24hr Video',
  '70 Lewis',
  '7HO3NIX',
  '89 Letters',
  'A Band Called Dreamland',
  'A-Go-Go',
  'Abdullah',
  'Abertooth Lincoln',
  'About Last Night',
  'ACCESSTOGOD',
  'Adam Paddock',
  'Adena Brook',
  'AJ Eustace',
  'all in ur head',
  'Aloe Vera',
  'Andi Jo / The Andi Jo Experience',
  'Andy Lang',
  'Annadale',
  'Ariadne',
  'Armand Rashad',
  'Armond WakeUp',
  'Art Grad',
  'ASAVA',
  'Baccano',
  'Bade',
  'Bathhousebetty',
  'Beaten Awake',
  'Beef',
  'Befriend Strange Creatures',
  'Being Grateful',
  'Ben Stalets',
  'Biitchseat',
  'Blasphemy Squad',
  'Blucone',
  'Blue Lunch',
  'Boatzz',
  'Bob Nicoloff & his Orchestra',
  'Body Farm',
  'Bone Thugs-N-Harmony',
  'Boulder',
  'Brave Face',
  'C-Money Baby',
  'Call Me Rita',
  'Cash K. Allen',
  'Cataracts',
  'Cattle Dogs',
  'Cedars Brothers',
  'Chad hates George',
  'Chalkline',
  'Cheap Clone',
  'Cherimondis J',
  'Cherry Yachtsman',
  'Chippewa Creek',
  'Choir Boy',
  'Choncy',
  'CHRIS.',
  'Chroma Cloud',
  'Circus',
  'City Lights',
  'City of Invention',
  'CityCop',
  'Cloudflower',
  'Coffin Makers',
  'Connor McLaren',
  'Cool Party',
  'Corker',
  'Coxey\'s Army',
  'craw',
  'Crime Light',
  'Crime of Passing',
  'Crown Shy',
  'Curtail',
  'DANA',
  'Danny Shipley Trio',
  'Dark Thoughts',
  'Darkroom',
  'Daywalker',
  'Dead Leaves',
  'Debris',
  'Designer',
  'Disintegration',
  'Distance Sprinter',
  'Divine Timing',
  'Doc Robinson',
  'Doe Boy',
  'Dogs Run Free',
  'Dom Deshawn',
  'Domestic Terror',
  'Douggert',
  'Draw the Line',
  'Dre Peace',
  'DripDaDon',
  'Driver Seat Passenger',
  'DRUMANITE',
  'Drummer',
  'Dèche',
  'Ebri Yahloe',
  'Electric Dream Machine',
  'Elevator Five',
  'Ella Choi',
  'Embleton',
  'En Love',
  'Exile & Eden',
  'Fairmount Girls',
  'False Teeth',
  'Felicity',
  'Femi and the Foundation',
  'Filmstrip',
  'Fistula',
  'FlowPoetry',
  'For Your Health',
  'Forever Unfolds',
  'Four Times Louder',
  'Freddie Losambe',
  'Friends with Elephants',
  'Fuck You Pay Me',
  'Fullsend',
  'Fun Junkies',
  'Funeral Commercial',
  'Fury & Solace',
  'Gardener',
  'Ghostman & Sandman',
  'Glümwalker',
  'Goldmines',
  'Gool',
  'GOROH',
  'Grace Favarro',
  'Green Heron',
  'Grumpy Plum',
  'Herzog',
  'Hey Monea!',
  'Hi-Tek',
  'Holy Kiss',
  'Honey & Blue',
  'Honolulu High',
  'Hoodoo Soul Band',
  'Hooked Like Helen',
  'Houseghost',
  'Houseguest',
  'HU-MID',
  'Huge Euge',
  'HummusVacuum',
  'Illogic',
  'Imber Solis',
  'In Flow',
  'Indoorfins',
  'Indré',
  'Ink',
  'Isicle',
  'Izzi Sleep',
  'J Rosa',
  'Jack Lutz',
  'Jady',
  'JayBee Lamahj',
  'Jinari Kemet',
  'Joe Brown / Joe Brown Band',
  'Joey Aich',
  'Jon Q Public',
  'Joseph and His Ghost',
  'JUSTYFI',
  'Karate Coyote',
  'Keelhaul',
  'Kid Cudi',
  'KID RICH',
  'Kid Tested',
  'Kill The Hippies',
  'Kim Beyer',
  'King Serpent',
  'Kudo',
  'Lakehorse',
  'Last Gasp',
  'Last Scouts',
  'Laughing Chimes',
  'Lauren Brabson',
  'Lavandula',
  'Lawton Brothers',
  'Leadfoot Granny',
  'Learner',
  'Leaving Off',
  'Legbone',
  'Levi Brown & The Smokin Section',
  'Lil Cray',
  'Lily Bloom',
  'Lisa Curtis',
  'Live Roots',
  'Lo V',
  'LoConti',
  'lossids',
  'Love as Laughter',
  'Love Thrill Murders',
  'Low Morale',
  'Lucky Shot',
  'Luna Falling',
  'Lung',
  'M.C. Brains',
  'Ma Holos',
  'Madd Mardigans',
  'Manor Gates',
  'Maria etc',
  'Maria etc.',
  'Marty Connor',
  'Me Time',
  'Me:You',
  'Melonhead',
  'MEOWBOYS',
  'Mezclado',
  'Middle Clash',
  'Mild-Mannered',
  'Mind Canaries',
  'Minnows',
  'Minuet',
  'Miracle Mile',
  'Moe Reen',
  'MOIRA',
  'Mojoflo',
  'Monday Night Big Band',
  'Moonbeau',
  'Motel Beds',
  'Mr. Gnome',
  'Mt. Air',
  'Mud Whale',
  'Mudhouse',
  'NEVERNEW',
  'New Bomb Turks',
  'Nixon Now',
  'Noah Smith',
  'Noah Wotherspoon Band',
  'Nodes',
  'Obnox',
  'Off Home Road',
  'OG Vern',
  'Oh Condor',
  'Oliver Hazard',
  'Orefice Roth',
  'Owls of Ohio',
  'PAL',
  'Palefire',
  'Part Time Lover',
  'Party of Helicopters',
  'People in the Daytime',
  'Personality Crisis',
  'Phinger Guns',
  'Pink Maskerade',
  'Placid State',
  'Pleasure Leftists',
  'Pop Music Fever Dream',
  'Pretty Pretty Awful',
  'Pro Skater',
  'Profligate',
  'Purple Bois',
  'Rabbit Dog',
  'Radderall',
  'Radio Dummies',
  'Ragamuffin',
  'Ragers',
  'Ramblewood',
  'Ray Cash',
  'Rebreather',
  'Red Sun Rising',
  'Rejoice',
  'Resignation',
  'RHY',
  'Ria Blaq',
  'Riley!',
  'Roid Rage',
  'Rosàna',
  'Rubber City Rebels',
  'Rue',
  'Run Rabbit Run',
  'S.M.I.L.E.',
  'Saintseneca',
  'Salt',
  'Samarra',
  'Sarah Cowan',
  'Saylor Rigsby',
  'Scarlet Street',
  'Scary Hotel',
  'see you',
  'SEV7N',
  'Shitbox Jimmy',
  'Sign Language',
  'Signals Midwest',
  'Simon Molnar',
  'Sink',
  'Sir Echo',
  'Sister Smirk',
  'SLUG',
  'smallboats',
  'Smug Brothers',
  'Snarls',
  'Sneak Thief',
  'Snitch Bastard Judas',
  'Sofa King Killer',
  'Softstone Hearts',
  'Solo Flyer',
  'Sons of April',
  'SOUR',
  'Sower',
  'Space Kid',
  'Sparky & the Hills',
  'Speaking Suns',
  'Spike Pit',
  'Stimulus Package',
  'Sugardeer',
  'Suitor',
  'Summore',
  'Sunset Junkies',
  'Surrender the Ghost',
  'Swansea Skag',
  'Swearing at Motorists',
  'Tall Grass',
  'Ted Hattemer',
  'Ten High',
  'The Behest of Serpents',
  'The Bizarros',
  'The Black Order',
  'The Blacklisted',
  'The Carp',
  'The Dead Pirate Disco',
  'The Deal Breakers',
  'The DollyHoppers',
  'The Dopamines',
  'The Drin',
  'The Entire History of You',
  'The Gross Outs',
  'The Hot Magnolias',
  'The Houseguest',
  'The Lycan Bite',
  'The Mimes',
  'The Missing',
  'The OG Players',
  'The Orphan & The Poet',
  'The Pseudofacts',
  'The Raging Nathans',
  'The Reedy Weeps',
  'The Serfs',
  'The Shadow Division',
  'The Smokey Honey Bluesband',
  'The Stereoflowers',
  'The Story Changes',
  'The Stretchers',
  'The Trio',
  'The Turkeys',
  'The Villaintinos',
  'The Vindys',
  'The Violent',
  'The Vumms',
  'The Way',
  'Third Culture Kid',
  'This Violet Hour',
  'Time Cat',
  'Tino',
  'TON',
  'Touchdown Jesus',
  'TraumaxQueen',
  'TRUSS',
  'Two Mile Moon',
  'Unbyul',
  'Unseen Keys',
  'Vacation',
  'Valley of the Sun',
  'Velvet Green',
  'Villagerrr',
  'Vision Swords',
  'Vitruvian Soul',
  'Wax Teeth',
  'Well Read',
  'Who Saved Who',
  'Wine Lips',
  'Wondelone',
  'Wussy',
  'Xanny Stars',
  'Yacobucci',
  'Yambag',
  'Year Twins',
  'YelloPain',
  'Yeshayuh',
  'YFL Kelvin',
  'Young Genesis',
  'YSN Flow',
  'Yuppie',
  'Zaylen',
  'Zelly Ocho',
  'Zoo Trippin\'',
];
